### ISSUE TITLE
handleNavigationQueue infinite loop

### ISSUE THREAD

**Issue by pwiet01** [FireboltCasters/kitcheningredients#4]
Items are not removed from queueCopy, which results in an infinite while loop.

https://github.com/FireboltCasters/kitcheningredients/blob/bd7ab38ca2f4a746928bdabc8ffe8bd6c7849371/app/src/api/src/ignoreCoverage/KitchenHelper/navigation/NavigatorHelper.ts#L157-L167

**Comment by pwiet01** [comment]
This method is also never called. Should probably be called in RootComponent's onReady method.

**Comment by NilsBaumgartner1994** [comment]
fix in #257
